name             'app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Production setup'
long_description 'Production setup'
version          '0.1.0'

depends 'apache2'
depends 'mysql'
depends 'php'
depends 'composer'
depends 'nodejs'
