version: '2'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net01
  php:
    image: php:fpm
    container_name: php
    volumes:
      - .:/var/www/app
    links:
      - db
    networks:
      - net01
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
    networks:
      - net01

networks:
  net01:
    driver: bridge
