name             'mycookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mycookbook'
long_description 'Installs/Configures mycookbook'
version          '0.1.0'

depends 'apt'
depends 'apache2'
depends 'mysql'
depends 'php'
depends 'composer'
depends 'nodejs'
