name             'dev'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Development setup'
long_description 'Development setup'
version          '0.1.0'

depends 'app'
depends 'apache2'
depends 'mysql'
depends 'composer'
depends 'xdebug'
